# This is a basic workflow that is manually triggered

name: Frontend build docker image and remote ssh pull & run

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches: [frontend]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  build_pull_run:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2 # Checking out the repo

      - name: Build and Publish head Docker image
        uses: VaultVulp/gp-docker-action@1.1.7
        with:
          github-token: ${{ secrets.GITTOKEN }} # Provide GITHUB_TOKEN to login into the GitHub Packages
          image-name: frontend # Provide Docker image name
          image-tag: head # Provide Docker image tag

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSHUSER }}
          password: ${{ secrets.SSHPASSWORD }}
          script:
            docker pull docker.pkg.github.com/dr124/vii-resource-management/frontend:head;
            docker kill frontend;
            docker stop frontend;
            docker rm frontend;
            docker rmi $(docker images --filter "dangling=true" -q --no-trunc);
            docker run -d -p 8000:80 --name frontend docker.pkg.github.com/dr124/vii-resource-management/frontend:head
